// TGO T-VER registry snapshot tests. The snapshot is regenerated by `scripts/ingest/tgo.py`; this file
// asserts that the published totals stay self-consistent and that no province drops a multi-province or
// unlocated project. Conservation: province single + multi + unlocated = national for every additive count.
import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';

const d=JSON.parse(readFileSync('public/data/tgo/tver-forestry.json','utf8'));
const close=(a,b,rel=1e-5)=>assert.ok(Math.abs(a-b)<=rel*Math.max(Math.abs(a),Math.abs(b),1),`${a} vs ${b}`);

test('snapshot covers FOR&AGR projects with a snapshot timestamp and source links',()=>{
  assert.equal(d.schemaVersion,1);
  assert.match(d.snapshot,/^\d{4}-\d{2}-\d{2}$/,'snapshot must be ISO date');
  assert.equal(typeof d.source.raw_sha256,'string');
  assert.equal(d.source.raw_sha256.length,64);
  assert.match(d.source.registry,/^https:\/\/tver\.tgo\.or\.th\//);
  assert.equal(d.scope.includes('FOR&AGR'),true);
});

test('national totals add up: single + multi + unlocated = national for every count',()=>{
  const provs=d.provinces;
  for(const k of ['projects','expected_tco2e_yr','issued_tco2e']){
    const sum=Object.values(provs).reduce((a,p)=>a+p[k],0)+d.multi[k]+d.unlocated[k];
    close(sum,d.national[k],1e-4);
  }
});

test('issuance records sum to each project list total (no missing rows)',()=>{
  for(const p of d.projects){
    const sum=p.issuances.reduce((a,i)=>a+(i.tco2e||0),0);
    close(sum,p.issued_tco2e,1e-4);
  }
});

test('multi_province_projects counter matches the multi bucket and the project list',()=>{
  // Each province with at least one multi-province project should count those projects.
  let counterSum=0;
  for(const p of d.projects.filter(x=>x.provinces.length>1))for(const pc of p.provinces)counterSum++;
  let bucketSum=0;
  for(const p of Object.values(d.provinces))bucketSum+=p.multi_province_projects;
  close(counterSum,bucketSum,1e-4);
  // And each multi project adds 1 to d.multi.projects.
  close(d.multi.projects,d.projects.filter(p=>p.provinces.length>1).length,1e-4);
});

test('every province code is one of the 77 official codes (no synthetic codes leaked in)',()=>{
  const codes=new Set(Object.keys(d.provinces));
  assert.equal(codes.size,77);
  for(const p of d.projects)for(const pc of p.provinces)assert.ok(codes.has(pc),`unknown province code ${pc} in ${p.key}`);
});

test('reviewer notes are attached only to projects marked reviewed',()=>{
  for(const p of d.projects){
    if(p.province_basis==='reviewed')assert.ok(p.province_note&&p.province_note.length>0,`${p.key} reviewed but no note`);
    else assert.equal(p.province_note,null);
  }
});

test('expected_tco2e_yr is null or a positive number; issued_tco2e is non-negative',()=>{
  for(const p of d.projects){
    if(p.expected_tco2e_yr!=null)assert.ok(p.expected_tco2e_yr>0);
    assert.ok(p.issued_tco2e>=0);
    assert.ok(p.issued_tco2e<=p.expected_tco2e_yr*200,'issued within an order of magnitude of expected');
  }
});

test('OTC market has at least one year of FOR&AGR data with sensible price and volume',()=>{
  const rows=d.market.for_agr;
  assert.ok(rows.length>=1);
  for(const r of rows){
    assert.ok(r.year>=2020&&r.year<=2100);
    assert.ok(r.volume_tco2e>0);
    assert.ok(r.avg_thb>0&&r.min_thb>0&&r.max_thb>=r.min_thb);
  }
});

test('projects with issuances are a subset of the project list and their issuance dates are within the crediting period',()=>{
  const withIssue=d.projects.filter(p=>p.issuances.length>0);
  assert.equal(withIssue.length,d.national.projects_with_issuance);
  for(const p of withIssue){
    for(const i of p.issuances){
      if(p.credit_start&&i.certified)assert.ok(i.certified>=p.credit_start,`${p.key} issuance ${i.certified} before crediting start ${p.credit_start}`);
      if(p.credit_end&&i.certified)assert.ok(i.certified<=p.credit_end,`${p.key} issuance ${i.certified} after crediting end ${p.credit_end}`);
    }
  }
});

test('TGO source is cited in both research notebooks (T-VER section)',()=>{
  for(const lang of ['en','th']){
    const doc=readFileSync(`docs/RESEARCH.${lang}.md`,'utf8');
    assert.ok(/tver\.tgo\.or\.th|T-VER|ทะเบียน T-VER/i.test(doc),`TGO registry not cited in ${lang} notebook`);
  }
});

test('portfolio program breakdown: Standard vs Premium T-VER projects are recognized',()=>{
  const std=d.projects.filter(p=>p.program==='standard');
  const prem=d.projects.filter(p=>p.program==='premium');
  assert.equal(std.length+prem.length,d.projects.length);
  assert.ok(prem.length>=10,'Premium T-VER has at least 10 projects');
  assert.ok(std.length>=240,'Standard T-VER forms the majority of historical registrations');
});

test('all project methodology families map to valid known family keys',()=>{
  const validFamilies=new Set(['ar','redd','ar_large','plantation','mangrove','ifm','agri_land','perennial','peat']);
  for(const p of d.projects){
    for(const f of p.families){
      assert.ok(validFamilies.has(f),`invalid family ${f} in project ${p.key}`);
    }
  }
});

test('issuance rate matches the documented 12% issuance cliff (31 of 257)',()=>{
  const issuedProjects=d.projects.filter(p=>p.issued_tco2e>0);
  assert.equal(issuedProjects.length,31);
  assert.equal(d.projects.length,257);
  const rate=issuedProjects.length/d.projects.length;
  assert.ok(rate>0.11&&rate<0.13,'issuance rate is approximately 12.1%');
});