const f=(n,d=2)=>new Intl.NumberFormat('en-US',{maximumFractionDigits:d}).format(n);
export function auditView(a,lang){
 const th=lang==='th';
 const table=(headers,rows)=>`<div class="table-scroll"><table><thead><tr>${headers.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(x=>`<td>${x}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
 return `<section class="audit-results"><h3>${th?'ผลที่รันได้จากข้อมูลที่ระบบใช้อยู่':'Executed diagnostics on deployed data'}</h3><p>${th?'วิเคราะห์ 77 จังหวัดด้วยโค้ดที่รันซ้ำได้ ตัวเลขนี้ตรวจการคำนวณและความไว ไม่ใช่ผลทวนสอบภาคสนาม':'A reproducible analysis of 77 provinces. These results test arithmetic and sensitivity; they are not field-validation results.'} · <a href="data/scientific-audit.json" target="_blank" rel="noopener">JSON + SHA-256 ↗</a></p>
 ${table(th?['รายการ','ผล','ความหมาย']:['Diagnostic','Result','Interpretation'],[[th?'ช่วงสุ่มระดับประเทศ':'National random-error half-range',`±${f(a.national.central_random_half95_pct)}%`,th?'แบบบล็อกและสมมติฐานปกติ ไม่รวมอคติเชิงระบบ':'Block and normal assumptions; systematic bias excluded'],[th?'มัธยฐานช่วงสุ่มจังหวัด':'Median provincial random-error half-range',`±${f(a.national.province_median_central_half95_pct)}%`,th?'77 จังหวัด ไม่ใช่ค่า RMSE จากภาคสนาม':'77 provinces; not field RMSE'],[th?'การเปลี่ยน R สมมติ +0.05':'Hypothetical R +0.05',`+${f(a.parameterSensitivity.scenarios.find(s=>s.id==='R-plus').relative_pct)}%`,th?'ความไวเชิงพีชคณิต ไม่ใช่ช่วงความเชื่อมั่น':'Algebraic sensitivity; not a confidence interval'],[th?'การเปลี่ยน CF สมมติ +0.01':'Hypothetical CF +0.01',`+${f(a.parameterSensitivity.scenarios.find(s=>s.id==='CF-plus').relative_pct)}%`,th?'ไม่มีการเปลี่ยนค่าตัวคูณในเครื่องมือ':'Calculator factors unchanged']])}
 <h3>${th?'ผลต่างสองวันที่ขึ้นกับความสัมพันธ์ของความคลาดเคลื่อน':'Two-date change depends on error correlation'}</h3><p>${th?'ตัวอย่างสมมติ: SD ของสต็อกแต่ละวัน = 10 tCO₂ ผลต่างที่เห็น = 20 tCO₂ ค่า ρ ไม่ได้ประมาณจากระบบนี้':'Hypothetical: stock SD at each date = 10 tCO₂; observed difference = 20 tCO₂. The app does not estimate ρ.'}</p>${table(['ρ',th?'ครึ่งช่วง 95% สมมติ (tCO₂)':'Hypothetical 95% half-range (tCO₂)',th?'ช่วงผลต่างคร่อมศูนย์?':'Difference interval includes zero?'],a.changeSensitivity.results.map(x=>[x.rho,f(x.half95),x.half95>=20?(th?'ใช่':'Yes'):(th?'ไม่':'No')]))}
 <h3>${th?'ความไวต่อการนับขอบกริด':'Sensitivity to grid-edge sampling'}</h3><p>${th?'รูปสามเหลี่ยมตัวอย่างหนึ่งรูปบนกริดจริง 16×16 เป็นเพียงค่าประมาณที่ถี่กว่า ไม่ใช่ค่าจริงหรือขอบเขตความผิดพลาดทั่วไป':'One illustrative triangle on the actual grid. 16×16 is a denser approximation, not truth or a general error bound.'}</p>${table(th?['จุดต่อด้าน','AGB (ตัน)','ต่างจาก 16×16']:['Samples per side','AGB (tonnes)','Difference from 16×16'],a.polygonSensitivity.results.map(x=>[x.samples_per_side,f(x.agb_mg),f(x.agb_difference_from_16_pct)+'%']))}
 <h3>${th?'วางแผนสำรวจ โดยไม่เดาจำนวนแปลงตายตัว':'Plan sampling without inventing a fixed plot count'}</h3><p>${th?'CV คือ SD หารค่าเฉลี่ย e คือครึ่งช่วงสัมพัทธ์ที่ต้องการ design effect คืออัตราส่วนความแปรปรวนของแบบสุ่มจริงต่อแบบสุ่มอิสระ สูตรวางแผนสมมติ n ≈ ceil[(1.96 × CV / e)² × design effect] ที่ e = 10% ต้องประมาณ CV และโครงสร้างการสุ่มจาก pilot ก่อน ไม่ใช่ขั้นต่ำของ อบก.':'CV = SD / mean; e is the target relative half-width; design effect is design variance divided by independent-sample variance. Illustrative planning: n ≈ ceil[(1.96 × CV / e)² × design effect], with e = 10%. Pilot estimates of CV and the sampling structure are required. These are not TGO minimums.'}</p>${table(['CV',th?'หน่วยอิสระ':'Independent units','Design effect = 2'],a.samplingDesign.results.map(x=>[x.cv,x.independent_units,x.units_with_design_effect_2]))}
 <h3>${th?'รุ่นข้อมูลที่ใช้ในงานตรวจนี้':'Dataset versions used in this audit'}</h3>${table(th?['ชุดข้อมูล','รุ่น','ช่วง / ปี']:['Dataset','Version','Period / year'],Object.entries(a.datasetVersions).map(([id,d])=>[id,d.version,d.period??'—']))}
 <p class="fine-print">${th?'รันจากข้อมูลที่มี hash ใน JSON; ทุกสมมติฐานเก็บแยกจากผลวัด ไม่มีการฝึกโมเดลใหม่ ประเมิน additionality ภาคสนาม หรือพิสูจน์ความครอบคลุมของช่วง 95%':'Input hashes are in the JSON; hypothetical assumptions are separate from observations. No new model training, field additionality assessment or proof of 95% interval coverage was performed.'} · ${a.date} · ${a.commit}</p></section>`;
}
